// export const infinitive: string[] =  [
//     "Agree",
//     "Refuse",
//     "Promise",
//     "Threaten",
//     "Offer",
//     "Attempt",
//     "Manage",
//     "Fail",
//     "Decide",
//     "Plan",
//     "Arrange",
//     "Hope",
//     "Appear",
//     "Seem",
//     "Pretend",
//     "Afford",
//     "Forget",
//     "Learn",
//     "Teach",
//     "Enable",
//     "Persuade",
//     "Get",
//     "Warn",
//     "Dare",
//     "Tend",
//     "Would like",
//     "Would love",
//     "Would prefer",
//     "Desire",
//     "Intend ",
//     "Claim to",
//     "Want",
//     "Hesitate",
//     "Wish",
//     "Demand",
//     "Strive",
//     "Expect",
//     "Advise",
//     "Ask",
//     "Allow",
//     "Encourage",
//     "Deserve",
//     "Force",
//     "Invite",
//     "Help",
//     "Mean",
//     "Order",
//     "Tell",
//     "Aim"
// ];

//   export const gerung: string[] =  [
//     "Stop",
//     "Finish",
//     "Delay",
//     "Enjoy",
//     "Mind",
//     "Suggest",
//     "Fancy",
//     "Imagine",
//     "Admit",
//     "Deny",
//     "Avoid",
//     "Consider",
//     "Involve",
//     "Practice",
//     "Miss",
//     "Postpone",
//     "Put off",
//     "Risk",
//     "Mention",
//     "Give up",
//     "Go on",
//     "Carry on",
//     "Keep",
//     "Keep on",
//     "Appreciate",
//     "Report",
//     "Resent",
//     "Quit",
//     "Resist",
//     "Recall",
//     "Resume",
//     "Prevent",
//     "Hate"
// ];

export const infinitive = [
    ["Agree", "Соглашаться"],
    ["Refuse", "Отказываться"],
    ["Promise", "Обещать"],
    ["Threaten", "Угрожать"],
    // ["Offer", "Предлагать"],
    // ["Attempt", "Пытаться"],
    // ["Manage", "Управлять"],
    // ["Fail", "Проваливаться"],
    // ["Decide", "Решать"],
    // ["Plan", "Планировать"],
    // ["Arrange", "Устраивать"],
    // ["Hope", "Надеяться"],
    // ["Appear", "Появляться"],
    // ["Seem", "Казаться"],
    // ["Pretend", "Притворяться"],
    // ["Afford", "Позволить себе"],
    // ["Forget", "Забывать"],
    // ["Learn", "Учиться"],
    // ["Teach", "Учить"],
    // ["Enable", "Включать"],
    // ["Persuade", "Убеждать"],
    // ["Get", "Получать"],
    // ["Warn", "Предупреждать"],
    // ["Dare", "Сметь"],
    // ["Tend", "Тяготеть"],
    // ["Would like", "Хотеть"],
    // ["Would love", "Очень хотеть"],
    // ["Would prefer", "Предпочесть бы"],
    // ["Desire", "Желать"],
    // ["Intend ", "Намереваться"],
    // ["Claim to", "Утверждать"],
    // ["Want", "Хотеть"],
    // ["Hesitate", "Колебаться"],
    // ["Wish", "Желать"],
    // ["Demand", "Требовать"],
    // ["Strive", "Стремиться"],
    // ["Expect", "Ожидать"],
    // ["Advise", "Советовать"],
    // ["Ask", "Спрашивать"],
    // ["Allow", "Разрешать"],
    // ["Encourage", "Поддерживать"],
    // ["Deserve", "Заслуживать"],
    // ["Force", "Принуждать"],
    // ["Invite", "Приглашать"],
    // ["Help", "Помогать"],
    // ["Mean", "Значить"],
    // ["Order", "Приказывать"],
    // ["Tell", "Говорить"],
    // ["Aim", "Целиться"]
];

export const gerung = [
    ["Stop", "Остановить"],
    ["Finish", "Закончить"],
    ["Delay", "Откладывать"],
    ["Enjoy", "Наслаждаться"],
    // ["Mind", "Придираться"],
    // ["Suggest", "Предлагать"],
    // ["Fancy", "Представлять себе"],
    // ["Imagine", "Представлять"],
    // ["Admit", "Признавать"],
    // ["Deny", "Отрицать"],
    // ["Avoid", "Избегать"],
    // ["Consider", "Рассматривать"],
    // ["Involve", "Включать"],
    // ["Practice", "Практиковать"],
    // ["Miss", "Пропускать"],
    // ["Postpone", "Откладывать"],
    // ["Put off", "Откладывать"],
    // ["Risk", "Рисковать"],
    // ["Mention", "Упоминать"],
    // ["Give up", "Бросать"],
    // ["Go on", "Продолжать"],
    // ["Carry on", "Продолжать"],
    // ["Keep", "Держать"],
    // ["Keep on", "Продолжать"],
    // ["Appreciate", "Ценить"],
    // ["Report", "Сообщать"],
    // ["Resent", "Сердиться"],
    // ["Quit", "Бросать"],
    // ["Resist", "Сопротивляться"],
    // ["Recall", "Вспоминать"],
    // ["Resume", "Возобновлять"],
    // ["Prevent", "Предотвращать"],
    // ["Hate", "Ненавидеть"]
];

export const wrong = [
    ["Stop", "Остановить"],
    ["Finish", "Закончить"],
    ["Delay", "Откладывать"],
    ["Enjoy", "Наслаждаться"],
    ["Mind", "Придираться"],
    ["Suggest", "Предлагать"],
    ["Fancy", "Представлять себе"],
    ["Imagine", "Представлять"],
    ["Admit", "Признавать"],
    ["Deny", "Отрицать"],
    ["Avoid", "Избегать"],
    ["Consider", "Рассматривать"],
    ["Involve", "Включать"],
    ["Practice", "Практиковать"],
    ["Miss", "Пропускать"],
    ["Postpone", "Откладывать"],
    ["Put off", "Откладывать"],
    ["Risk", "Рисковать"],
    ["Mention", "Упоминать"],
    ["Give up", "Бросать"],
    ["Go on", "Продолжать"],
    ["Carry on", "Продолжать"],
    ["Keep", "Держать"],
    ["Keep on", "Продолжать"],
    ["Appreciate", "Ценить"],
    ["Report", "Сообщать"],
    ["Resent", "Сердиться"],
    ["Quit", "Бросать"],
    ["Resist", "Сопротивляться"],
    ["Recall", "Вспоминать"],
    ["Resume", "Возобновлять"],
    ["Prevent", "Предотвращать"],
    ["Hate", "Ненавидеть"]
];