export const infinitive: string[] =  [
    "Agree",
    "Refuse",
    "Promise",
    "Threaten",
    "Offer",
    "Attempt",
    "Manage",
    "Fail",
    "Decide",
    "Plan",
    "Arrange",
    "Hope",
    "Appear",
    "Seem",
    "Pretend",
    "Afford",
    "Forget",
    "Learn",
    "Teach",
    "Enable",
    "Persuade",
    "Get",
    "Warn",
    "Dare",
    "Tend",
    "Would like",
    "Would love",
    "Would prefer",
    "Desire",
    "Intend ",
    "Claim to",
    "Want",
    "Hesitate",
    "Wish",
    "Demand",
    "Strive",
    "Expect",
    "Advise",
    "Ask",
    "Allow",
    "Encourage",
    "Deserve",
    "Force",
    "Invite",
    "Help",
    "Mean",
    "Order",
    "Tell",
    "Aim"
  ];

  export const gerung: string[] =  [
    "Stop",
    "Finish",
    "Delay",
    "Enjoy",
    "Mind",
    "Suggest",
    "Fancy",
    "Imagine",
    "Admit",
    "Deny",
    "Avoid",
    "Consider",
    "Involve",
    "Practice",
    "Miss",
    "Postpone",
    "Put off",
    "Risk",
    "Mention",
    "Give up",
    "Go on",
    "Carry on",
    "Keep",
    "Keep on",
    "Appreciate",
    "Report",
    "Resent",
    "Quit",
    "Resist",
    "Recall",
    "Resume",
    "Prevent",
    "Hate"
  ];